### PR TITLE
Add a secure flag to uuidv4 to support cryptographically secure uuids

### PR DESCRIPTION
**Pull request by oleiade**
Our initial implementation of UUIDv4 used Math.Random(). This commit
adds a secure flag to the function which, when set to true, sets the
function to produce a cryptographically secure UUID instead.

The cryptographically secure implementation is mostly based on the [node package's](https://github.com/uuidjs/uuid/blob/main/src/v4.js).

### CODE REVIEW

**Review by sniku — APPROVED** [review]
LGTM. 

I'm interested in how much slower is the secure version?
Could we run 1 VU 60s test and compare the number of executions?

**Comment by oleiade** [comment]
@sniku When ran using the cryptographically secure algorithm, the `uuidv4` function is an order of magnitude slower (on a 12 cores/4ghz processor). 

Performed the test with the following script:

```javascript
import { uuidv4 } from "./src/utils.js";
import { Counter } from "k6/metrics";

export const options = {
  scenarios: {
    insecure: {
      executor: "constant-vus",
      vus: 1,
      duration: "60s",
      exec: "insecureUUIDv4",
    },

    secure: {
      executor: "constant-vus",
      vus: 1,
      duration: "60s",
      exec: "secureUUIDv4",
    },
  },
};

const insecureCounter = new Counter("insecure");
const secureCounter = new Counter("secure");

export function insecureUUIDv4() {
  uuidv4();
  insecureCounter.add(1);
}

export function secureUUIDv4() {
  uuidv4(true);
  secureCounter.add(1);
}
```

We get the following results:
```
     iterations...........: 1587927 26464.9222/s
     secure...............: 215216  3586.861799/s
```

**Comment by sniku** [comment]
That's a neat test :-) Thanks for running it.

**Comment by oleiade** [comment]
https://github.com/grafana/k6-jslib-utils/pull/8 is blocking this merge.

**Comment by oleiade** [comment]
Now that #8 is merged, I'll go ahead an merge this, unless anybody opposes, in the upcoming days 🤞🏻

**Pull request merged**
