### PR TITLE
Build exporting all the functions 

### PR DESCRIPTION
**Pull request by codebien**
It fixes the generated `index.js` file exporting all the utils functions. Apparently defining an array for the entry point is not working as expected.

If you have any suggestions for doing it smarter let me know.

Note: We haven't yet published the latest tag so I'm going to delete it and re-tag it after we will have merged this PR.

### CODE REVIEW

**Review by javaducky — APPROVED** [review]
LGTM as far as I can tell. I pulled down the code and ran the `npm run webpack` successfully. 

Caveat: I did *not* try using the produced artifacts.

**Review by sniku — CHANGES_REQUESTED** [review]
Something is not quite right. It throws exceptions when running the tests in the jslib repo. 
image
the same test works with the current version of k6-utils

**Comment by codebien** [comment]
@sniku are you using the expected next k6 version for running the tests? Unfortunately, the code doesn't support the previous versions, because it requires `k6/execution.test.options` only available from the `v0.38.0`.
I'm testing using an `xk6` version from the master with `xk6 build master`.

 :thinking: Considering it, should we bump a major version instead of a minor? There isn't a direct breaking change with the `k6-utils` API so I think it shouldn't be required. Maybe it could be good to be explicit in the various docs about the k6 requirement.

**Comment by sniku** [comment]
I don't think we can make an assumption that every k6-utils user is using the latest k6 version. 
If we do require a new version then we should raise a specific exception such as `raise Exception("This k6-util function requires k6 0.38 or later. Please upgrade")`.

**Review by sniku — APPROVED** [review]

**Pull request merged**
